CONFIG_ZMK_POINTING=y
CONFIG_ZMK_KEYBOARD_NAME="forager_sk"

# Enable experimental connection settings (disables 2M PHY to fix Realtek/Linux reconnect aborts)
CONFIG_ZMK_BLE_EXPERIMENTAL_CONN=y

# Increase Bluetooth transmit power for a more robust signal
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y
